// <auto-generated />
using System;
using HRPerformanceSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRPerformanceSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260429080317_AddUserIdToEmployee")]
    partial class AddUserIdToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("HRPerformanceSystem.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FullTimeAbsentDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FullTimeLateMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartTimeAbsentDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartTimeLateMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quarter")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId", "Month");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("EntityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NewValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("OldValues")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.CompetencyEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Q1M1Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q1M2Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q1M3Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q2M1Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q2M2Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q2M3Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q3M1Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q3M2Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q3M3Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q4M1Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q4M2Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q4M3Rating")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("Competencies");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AttendanceType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharterType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectManager")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Department");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttendanceType = 0,
                            CharterType = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "الموارد البشرية",
                            DirectManager = "خالد السعيد",
                            Email = "",
                            EmployeeNumber = "EMP001",
                            FullName = "أحمد محمد العمري",
                            IsActive = true,
                            IsDeleted = false,
                            JobTitle = "مدير إدارة",
                            Phone = ""
                        },
                        new
                        {
                            Id = 2,
                            AttendanceType = 0,
                            CharterType = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "الموارد البشرية",
                            DirectManager = "أحمد محمد العمري",
                            Email = "",
                            EmployeeNumber = "EMP002",
                            FullName = "فاطمة عبدالله الشمري",
                            IsActive = true,
                            IsDeleted = false,
                            JobTitle = "أخصائي موارد بشرية",
                            Phone = ""
                        },
                        new
                        {
                            Id = 3,
                            AttendanceType = 0,
                            CharterType = 0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Department = "تقنية المعلومات",
                            DirectManager = "سارة الحربي",
                            Email = "",
                            EmployeeNumber = "EMP003",
                            FullName = "محمد سعد الدوسري",
                            IsActive = true,
                            IsDeleted = false,
                            JobTitle = "محلل بيانات",
                            Phone = ""
                        });
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Link")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsRead");

                    b.HasIndex("TargetUserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.ObjectiveGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AchievementCriteria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("AnnualTarget")
                        .HasColumnType("REAL");

                    b.Property<string>("DataSource")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enablers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvidenceM1")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM10")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM11")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM12")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM2")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM3")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM4")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM5")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM6")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM7")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM8")
                        .HasColumnType("TEXT");

                    b.Property<string>("EvidenceM9")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoalDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationalIndicator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Q1M1Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q1M1Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q1M2Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q1M2Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q1M3Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q1M3Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q2M1Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q2M1Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q2M2Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q2M2Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q2M3Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q2M3Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q3M1Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q3M1Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q3M2Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q3M2Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q3M3Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q3M3Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q4M1Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q4M1Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q4M2Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q4M2Target")
                        .HasColumnType("REAL");

                    b.Property<double>("Q4M3Actual")
                        .HasColumnType("REAL");

                    b.Property<double>("Q4M3Target")
                        .HasColumnType("REAL");

                    b.Property<string>("StrategicIndicator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategicObjective")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.PerformanceEvaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EvaluationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MonthsStatusJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Q1Score")
                        .HasColumnType("REAL");

                    b.Property<double>("Q2Score")
                        .HasColumnType("REAL");

                    b.Property<double>("Q3Score")
                        .HasColumnType("REAL");

                    b.Property<double>("Q4Score")
                        .HasColumnType("REAL");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("EmployeeId", "Year");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.SurveyResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Answer")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EvaluationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.ToTable("SurveyResults");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.Property<byte[]>("CredentialId")
                        .HasMaxLength(1024)
                        .HasColumnType("BLOB");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CredentialId");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserPasskeys", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.AttendanceRecord", b =>
                {
                    b.HasOne("HRPerformanceSystem.Models.PerformanceEvaluation", "Evaluation")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.CompetencyEvaluation", b =>
                {
                    b.HasOne("HRPerformanceSystem.Models.PerformanceEvaluation", "Evaluation")
                        .WithMany("Competencies")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.ObjectiveGoal", b =>
                {
                    b.HasOne("HRPerformanceSystem.Models.PerformanceEvaluation", "Evaluation")
                        .WithMany("Goals")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.PerformanceEvaluation", b =>
                {
                    b.HasOne("HRPerformanceSystem.Models.Employee", "Employee")
                        .WithMany("Evaluations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.SurveyResult", b =>
                {
                    b.HasOne("HRPerformanceSystem.Models.PerformanceEvaluation", "Evaluation")
                        .WithMany("SurveyResults")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("HRPerformanceSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("HRPerformanceSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserPasskey<string>", b =>
                {
                    b.HasOne("HRPerformanceSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Microsoft.AspNetCore.Identity.IdentityPasskeyData", "Data", b1 =>
                        {
                            b1.Property<byte[]>("IdentityUserPasskeyCredentialId");

                            b1.Property<byte[]>("AttestationObject")
                                .IsRequired();

                            b1.Property<byte[]>("ClientDataJson")
                                .IsRequired();

                            b1.Property<DateTimeOffset>("CreatedAt");

                            b1.Property<bool>("IsBackedUp");

                            b1.Property<bool>("IsBackupEligible");

                            b1.Property<bool>("IsUserVerified");

                            b1.Property<string>("Name");

                            b1.Property<byte[]>("PublicKey")
                                .IsRequired();

                            b1.Property<uint>("SignCount");

                            b1.PrimitiveCollection<string>("Transports");

                            b1.HasKey("IdentityUserPasskeyCredentialId");

                            b1.ToTable("AspNetUserPasskeys");

                            b1
                                .ToJson("Data")
                                .HasColumnType("TEXT");

                            b1.WithOwner()
                                .HasForeignKey("IdentityUserPasskeyCredentialId");
                        });

                    b.Navigation("Data")
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRPerformanceSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("HRPerformanceSystem.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.Employee", b =>
                {
                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("HRPerformanceSystem.Models.PerformanceEvaluation", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Competencies");

                    b.Navigation("Goals");

                    b.Navigation("SurveyResults");
                });
#pragma warning restore 612, 618
        }
    }
}
